    - name: Sync
      uses: joshcai/leetcode-sync@v1.3
      with:
        github-token: ${{ secrets.AUTH_TOKEN }}
        github-token: ${{ github.token }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
        filter-duplicate-secs: 86400
