name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron:  '00 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Sync
      uses: joshcai/leetcode-sync@v1.3
      with:
        github-token: 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
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
        filter-duplicate-secs: 86400
